services:
  nest:
    container_name: hls-nest
    image: scharascher/hls-nest:task-2
    ports:
      - ${PORT}:${PORT}
    build: .
    volumes:
      - ./src:/app/src
    networks:
      - mynet
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public&connect_timeout=300
    restart: always
  postgres:
    container_name: hls-db
    image: scharascher/hls-db:task-2
    build:
      context: ./database
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  postgres_data: